// Code generated by sqlc-gen-ts-d1. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
//   sqlc-gen-ts-d1 v0.0.0-a@254c24db5bcb2e1e16559e7f8498d7fa673ada31

export type User = {
  id: string;
  screenName: string;
  displayName: string;
  passwordHashed: string;
  isActive: number | string;
  isProtected: number | string;
  bio: string | null;
  avatarUrl: number | string | null;
};

export type Post = {
  id: string;
  authorId: string;
  referenceId: string | null;
  content: string;
};

export type FollowRelation = {
  id: number;
  followerId: string;
  followingId: string;
};

export type BlockRelation = {
  id: number;
  blockerId: string;
  blockingId: string;
};
